### ISSUE TITLE
Polynomial identity check failed in multiRangeProofVerifier

### ISSUE THREAD

**Issue by darioAnongba** [BANKEX/BulletproofJS#2]
Hi,

I've been testing some values in the multiRangeProofVerifier and I get a `Polynomial identity check failed` when I tested it with number = 321 and change = 29 (I got rid of extra and zero).

This error appears randomly depending on the inputted values. Any idea why ? 

Cheers,
Dario

**Comment by shamatar** [comment]
Hello Dario.

If you use a MultiRangeProof, then the total proof capacity of N bytes is divided evenly between M values, and if any of the values exceeds the 2^(N/M) - 1 value, the proof becomes invalid.

Sincerely, Alex

________________________________

**Comment by darioAnongba** [comment]
Hi Alex, 

Thanks for the quick answer!

Indeed it's true that trying the same values with 32 bits does work with 321 and 29.

If I understand correctly and assuming that M is always 2 in my case, with 32 bits, the upper bound is 2^16 = 65'536 and was 2^8 before = 256, so that's why it failed? Because 321 is bigger than 256?

Thanks!

**Comment by shamatar** [comment]
Yes, MultiRange is not magical, it saves on scalar values, but number of field elements is still log2(fullConcatenatedBitLength). Nevertheless it’s handy in practice, especially if you enforce same length proofs for each of the commitments

________________________________
